runtime: python37
env_variables:
  FLASK_SECRET_KEY: placeholder
  DB_USER: placeholder
  DB_PASS: placeholder
  DB_NAME: placeholder
  DB_HOST: placeholder
  DB_PORT: placeholder
  CLOUD_SQL_CONNECTION_NAME: placeholder
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
