runtime: python37
env_variables:
  FLASK_SECRET_KEY: placeholder
  APP_DB_USER: placeholder
  APP_DB_PASS: placeholder
  APP_DB_NAME: placeholder
  APP_DB_HOST: placeholder
  APP_DB_PORT: placeholder
  EXAMPLE_DB_NAME: placeholder
  CLOUD_SQL_CONNECTION_NAME: placeholder
  CLOUD_TASK_QUEUE: placeholder
handlers:
- url: /images
  secure: always
  static_dir: static/images
- url: /scripts
  secure: always
  static_dir: static/scripts
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
