"""empty message

Revision ID: 05cdb79f9cb2
Revises: b843e4105265
Create Date: 2019-10-02 11:35:01.726645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05cdb79f9cb2'
down_revision = 'b843e4105265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=128), nullable=True))
    op.drop_column('user', 'test_2')
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('test_2', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
